### ISSUE TITLE
Does not run on Java 10

### ISSUE THREAD

**Issue by slagyr** [unclebob/spacewar#1]
With Java 10, the following error is encountered.  The problem is originates from the Processing library, used by the Quil library.  

Documented here: https://github.com/quil/quil/issues/228

I attempted to build and install the Quil Master (2.7.2-SNAPSHOT) which updates the version of Processing... no luck.  Same error.

$ lein run
java.lang.NoClassDefFoundError: com/apple/eawt/QuitHandler, compiling:(/private/var/folders/t7/lw3_q5mn0rndcfr4dtv4kp640000gn/T/form-init15250232525848975512.clj:1:126)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoClassDefFoundError: com/apple/eawt/QuitHandler
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3260)
	at java.base/java.lang.Class.getMethod0(Class.java:3246)
	at java.base/java.lang.Class.getMethod(Class.java:2065)
	at processing.core.PApplet.runSketch(PApplet.java:10707)
	at quil.applet$applet_run.invokeStatic(applet.clj:84)
	at quil.applet$applet_run.invoke(applet.clj:81)
	at quil.applet$applet.invokeStatic(applet.clj:328)
	at quil.applet$applet.doInvoke(applet.clj:269)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at spacewar.core$_main.invokeStatic(core.clj:100)
	at spacewar.core$_main.doInvoke(core.clj:98)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:377)
	at user$eval149.invokeStatic(form-init15250232525848975512.clj:1)
	at user$eval149.invoke(form-init15250232525848975512.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.QuitHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 32 more

**Comment by webcpu** [comment]
Update project.clj.
`                 [quil "4.3.1563"]
`
